// ─── THEME ────────────────────────────────────────────────────────────────────
export const lightTheme = {
  "--bg": "#F8F8FB",
  "--bg-card": "#FFFFFF",
  "--bg-sidebar": "#373B53",
  "--bg-form": "#FFFFFF",
  "--bg-item-row": "#F9FAFE",
  "--bg-total": "#373B53",
  "--border": "#DFE3FA",
  "--input-border": "#DFE3FA",
  "--input-focus": "#7C5DFA",
  "--text-primary": "#0C0E16",
  "--text-secondary": "#7E88C3",
  "--text-muted": "#888EB0",
  "--text-on-dark": "#FFFFFF",
  "--text-on-total": "#FFFFFF",
  "--overlay": "rgba(0,0,0,0.5)",
};

export const darkTheme = {
  "--bg": "#141625",
  "--bg-card": "#1E2139",
  "--bg-sidebar": "#1E2139",
  "--bg-form": "#141625",
  "--bg-item-row": "#252945",
  "--bg-total": "#0C0E16",
  "--border": "#252945",
  "--input-border": "#252945",
  "--input-focus": "#7C5DFA",
  "--text-primary": "#FFFFFF",
  "--text-secondary": "#DFE3FA",
  "--text-muted": "#888EB0",
  "--text-on-dark": "#FFFFFF",
  "--text-on-total": "#FFFFFF",
  "--overlay": "rgba(0,0,0,0.7)",
};

export const STATUS_STYLES = {
  paid: { bg: "rgba(51,214,159,0.1)", color: "#33D69F", dot: "#33D69F" },
  pending: { bg: "rgba(255,143,0,0.1)", color: "#FF8F00", dot: "#FF8F00" },
  draft: { bg: "rgba(55,59,83,0.1)", color: "#373B53", dot: "#373B53" },
};

export const STATUS_STYLES_DARK = {
  paid: { bg: "rgba(51,214,159,0.1)", color: "#33D69F", dot: "#33D69F" },
  pending: { bg: "rgba(255,143,0,0.1)", color: "#FF8F00", dot: "#FF8F00" },
  draft: { bg: "rgba(223,227,250,0.1)", color: "#DFE3FA", dot: "#DFE3FA" },
};

// ─── SAMPLE DATA ─────────────────────────────────────────────────────────────
export const SAMPLE_INVOICES = [
  {
    id: "RT3080",
    clientName: "Jensen Huang",
    clientEmail: "jensen@example.com",
    status: "paid",
    invoiceDate: "2021-07-31",
    paymentTerms: "Net 30 Days",
    description: "Brand Identity",
    billFrom: { street: "19 Union Terrace", city: "London", postCode: "E1 3EZ", country: "United Kingdom" },
    billTo: { street: "106 Kendell Street", city: "Sharrington", postCode: "NR24 5WQ", country: "United Kingdom" },
    items: [{ name: "Brand Guidelines", qty: 1, price: 1800.9 }],
  },
  {
    id: "XM9141",
    clientName: "Alex Grim",
    clientEmail: "alexgrim@mail.com",
    status: "pending",
    invoiceDate: "2021-08-21",
    paymentTerms: "Net 30 Days",
    description: "Graphic Design",
    billFrom: { street: "19 Union Terrace", city: "London", postCode: "E1 3EZ", country: "United Kingdom" },
    billTo: { street: "84 Church Way", city: "Bradford", postCode: "BD1 9PB", country: "United Kingdom" },
    items: [
      { name: "Banner Design", qty: 1, price: 156.0 },
      { name: "Email Design", qty: 2, price: 200.0 },
    ],
  },
  {
    id: "RG0314",
    clientName: "John Morrison",
    clientEmail: "jm@myco.com",
    status: "paid",
    invoiceDate: "2021-09-01",
    paymentTerms: "Net 30 Days",
    description: "Web Development",
    billFrom: { street: "19 Union Terrace", city: "London", postCode: "E1 3EZ", country: "United Kingdom" },
    billTo: { street: "7 Sherwood Place", city: "Leeds", postCode: "LS2 7DX", country: "United Kingdom" },
    items: [{ name: "E-Commerce Website", qty: 1, price: 14002.33 }],
  },
  {
    id: "RT2080",
    clientName: "Alysa Werner",
    clientEmail: "alysa@mail.co.uk",
    status: "pending",
    invoiceDate: "2021-09-12",
    paymentTerms: "Net 30 Days",
    description: "UI/UX Design",
    billFrom: { street: "19 Union Terrace", city: "London", postCode: "E1 3EZ", country: "United Kingdom" },
    billTo: { street: "2 Cole Street", city: "Manchester", postCode: "M1 1AE", country: "United Kingdom" },
    items: [{ name: "UX Research", qty: 1, price: 102.04 }],
  },
  {
    id: "AA1449",
    clientName: "Mellisa Clarke",
    clientEmail: "mellisa@example.com",
    status: "pending",
    invoiceDate: "2021-09-14",
    paymentTerms: "Net 30 Days",
    description: "App Design",
    billFrom: { street: "19 Union Terrace", city: "London", postCode: "E1 3EZ", country: "United Kingdom" },
    billTo: { street: "46 Abbey Row", city: "Cambridge", postCode: "CB5 6EG", country: "United Kingdom" },
    items: [
      { name: "Logo Design", qty: 1, price: 1532.33 },
      { name: "App Design", qty: 1, price: 2500.0 },
    ],
  },
  {
    id: "TY9141",
    clientName: "Thomas Wayne",
    clientEmail: "thomas@wayne.com",
    status: "pending",
    invoiceDate: "2021-10-01",
    paymentTerms: "Net 30 Days",
    description: "Motion Design",
    billFrom: { street: "19 Union Terrace", city: "London", postCode: "E1 3EZ", country: "United Kingdom" },
    billTo: { street: "3 Gotham Ave", city: "Bristol", postCode: "BS1 4DD", country: "United Kingdom" },
    items: [{ name: "Animation Package", qty: 1, price: 6155.91 }],
  },
  {
    id: "FV2353",
    clientName: "Anita Wainwright",
    clientEmail: "anita@mail.com",
    status: "draft",
    invoiceDate: "2021-10-12",
    paymentTerms: "Net 30 Days",
    description: "Copywriting",
    billFrom: { street: "19 Union Terrace", city: "London", postCode: "E1 3EZ", country: "United Kingdom" },
    billTo: { street: "12 Peel Road", city: "Edinburgh", postCode: "EH3 5BD", country: "United Kingdom" },
    items: [{ name: "Blog Posts (x10)", qty: 1, price: 3102.04 }],
  },
];
